# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :testing do
    # begin
    #   run_tests(
    #     project: "DarkAndLightMode.xcodeproj",
    #     scheme: "DarkAndLightMode Internal",
    #   )
    # rescue => ex
    #   # Can be empty
    # end

    run_tests(
      project: "DarkAndLightMode.xcodeproj",
      scheme: "DarkAndLightMode Internal",
    )
    
  ensure
    puts "xcresult: #{lane_context[SharedValues::SCAN_GENERATED_XCRESULT_PATH]}"
    sh "envman add --key BITRISE_XCRESULT_PATH --value \"#{lane_context[SharedValues::SCAN_GENERATED_XCRESULT_PATH]}\""
  end
end
